export interface OfficialSeries {
    name: string
    licenseClass: "Rookie" | "D" | "C" | "B" | "A"
    url?: string
    src?: string
}

export const iRacing2024S1RoadSeries: OfficialSeries[] = [
        {name: 'Global Mazda MX‑5 Fanatec Cup', src: '/iracing/2024s1/GlobalMazda.png', licenseClass: 'Rookie'},
        {name: 'Formula Vee SIMAGIC Series', src: '/iracing/2024s1/Vee.png', licenseClass: 'Rookie'},
        {name: 'Formula 1600 Rookie Sim‑Motion Series Fixed', src: '/iracing/2024s1/Formula1600.png', licenseClass: 'Rookie'},
        {name: 'Ferrari GT3 Challenge Fixed', src: '/iracing/2024s1/FerrariGT3.png', licenseClass: 'D'},
        {name: 'GR Buttkicker Cup Fixed', src: '/iracing/2024s1/GRCup.png', licenseClass: 'D'},
        {name: 'Production Car Sim‑Lab Challenge', src: '/iracing/2024s1/PCC.png', licenseClass: 'D'},
        {name: 'Formula 1600 Thrustmaster Trophy', src: '/iracing/2024s1/FF1600D.png', licenseClass: 'D'},
        {name: 'FIA Formula 4 Challenge', src: '/iracing/2024s1/Formula4.png', licenseClass: 'D'},
        {name: 'FIA Formula 4 Challenge Fixed', src: '/iracing/2024s1/Formula4Fixed.png', licenseClass: 'D'},
        {name: 'GT4 Falken Tyre Challenge Fixed', src: '/iracing/2024s1/GT4Fixed.png', licenseClass: 'D'},
        {name: 'Weekly Race Challenge', src: '/iracing/2024s1/WeeklyRace.png', licenseClass: 'D'},
        {name: 'Global Fanatec Challenge', src: '/iracing/2024s1/GlobalFanatec.png', licenseClass: 'D'},
        {name: 'Skip Barber Race Series', src: '/iracing/2024s1/SkipBarber.png', licenseClass: 'D'},
        {name: 'Clio Cup Fixed', src: '/iracing/2024s1/ClioCup.png', licenseClass: 'D'},
        {name: 'Touring Car Challenge', src: '/iracing/2024s1/TCC.png', licenseClass: 'D'},
        {name: 'Touring Car Challenge Fixed', src: '/iracing/2024s1/TCCFixed.png', licenseClass: 'D'},
        {name: 'Spec Racer Ford Challenge', src: '/iracing/2024s1/SpecRacer.png', licenseClass: 'D'},
        {name: 'US Open Wheel D USF 2000 Series Fixed', src: '/iracing/2024s1/OpenWheelD.png', licenseClass: 'D'},
        {name: 'FIA F4 Esports Regional Tour Europe North', src: '/iracing/2024s1/F4RegionalEurNo.png', licenseClass: 'D'},
        {name: 'FIA F4 Esports Regional Tour Americas', src: '/iracing/2024s1/F4RegionalAmericas.png', licenseClass: 'D'},
        {name: 'FIA F4 Esports Regional Tour Europe South', src: '/iracing/2024s1/F4RegionalEurSo.png', licenseClass: 'D'},
        {name: 'FIA F4 Esports Regional Tour Asia Pacific', src: '/iracing/2024s1/F4RegionalAsiaPac.png', licenseClass: 'D'},
        {name: 'Mustang Skip Barber Challenge Fixed', src: '/iracing/2024s1/MustangBarber.png', licenseClass: 'D'},
        {name: 'Mission R Challenge Fixed', src: '/iracing/2024s1/MissionR.png', licenseClass: 'D'},
        {name: 'Falken Tyre Sports Car Challenge', src: '/iracing/2024s1/SCC.png', licenseClass: 'C'},
        {name: 'Proto‑GT Thrustmaster Challenge', src: '/iracing/2024s1/ProtoGT.png', licenseClass: 'C'},
        {name: 'Ring Meister Ricmotech Series Fixed', src: '/iracing/2024s1/RingMeister.png', licenseClass: 'C'},
        {name: 'iRacing Porsche Cup Fixed', src: '/iracing/2024s1/PorscheCupFixed.png', licenseClass: 'C'},
        {name: 'iRacing Porsche Cup', src: '/iracing/2024s1/PorscheCup.png', licenseClass: 'C'},
        {name: 'Formula C DOF Reality Dallara F3 Series', src: '/iracing/2024s1/FormulaC.png', licenseClass: 'C'},
        {name: 'Formula Thrustmaster Dallara F3 Series Fixed', src: '/iracing/2024s1/FormulaCFixed.png', licenseClass: 'C'},
        {name: 'GT Endurance VRS Series', src: '/iracing/2024s1/GTEndurance.png', licenseClass: 'C'},
        {name: 'IMSA Michelin Pilot Challenge Series', src: '/iracing/2024s1/IMSAPilot.png', licenseClass: 'C'},
        {name: 'Advanced Mazda MX‑5 Cup Series', src: '/iracing/2024s1/AdvancedMazda.png', licenseClass: 'C'},
        {name: 'LMP3 Turn Racing Trophy Fixed', src: '/iracing/2024s1/LMP3Trophy.png', licenseClass: 'C'},
        {name: 'Radical Esports Cup Fixed', src: '/iracing/2024s1/RadicalCup.png', licenseClass: 'C'},
        {name: 'Classic Lotus Grand Prix', src: '/iracing/2024s1/ClassicLotus.png', licenseClass: 'C'},
        {name: 'Dallara Formula iR Fixed', src: '/iracing/2024s1/FormulaiRFixed.png', licenseClass: 'C'},
        {name: 'IMSA Vintage Series', src: '/iracing/2024s1/IMSAVintage.png', licenseClass: 'C'},
        {name: 'Supercars Series', src: '/iracing/2024s1/SupercarsSeries.png', licenseClass: 'C'},
        {name: 'Supercars Series Australian Servers', src: '/iracing/2024s1/SupercarsSeriesAus.png', licenseClass: 'C'},
        {name: 'US Open Wheel C Indy Pro 2000 Series', src: '/iracing/2024s1/OpenWheelC.png', licenseClass: 'C'},
        {name: 'Grand Prix Legends', src: '/iracing/2024s1/GrandPrixLegends.png', licenseClass: 'C'},
        {name: 'Stock Car Brasil Fixed', src: '/iracing/2024s1/StockCarBrasil.png', licenseClass: 'C'},
        {name: 'GT3 Fanatec Challenge Fixed', src: '/iracing/2024s1/GT3Fixed.png', licenseClass: 'B'},
        {name: 'GT Sprint VRS Series', src: '/iracing/2024s1/GTSprint.png', licenseClass: 'B'},
        {name: 'Formula B Super Formula IMSIM Series Fixed', src: '/iracing/2024s1/SuperFormulaFixed.png', licenseClass: 'B'},
        {name: 'Formula B Super Formula IMSIM Series', src: '/iracing/2024s1/SuperFormula.png', licenseClass: 'B'},
        {name: 'Global Endurance Pure Driving School Tour', src: '/iracing/2024s1/GlobalEndurance.png', licenseClass: 'B'},
        {name: 'LMP2 Prototype Challenge Fixed', src: '/iracing/2024s1/LMP2Proto.png', licenseClass: 'B'},
        {name: 'GTE Sprint Pure Driving School Series', src: '/iracing/2024s1/GTESprint.png', licenseClass: 'B'},
        {name: 'IMSA Endurance Series', src: '/iracing/2024s1/IMSAEndurance.png', licenseClass: 'B'},
        {name: 'US Open Wheel B Dallara IR‑18', src: '/iracing/2024s1/OpenWheelB.png', licenseClass: 'B'},
        {name: 'Formula B Formula Renault 3.5 Series', src: '/iracing/2024s1/FormulaB.png', licenseClass: 'B'},
        {name: 'IMSA iRacing Series', src: '/iracing/2024s1/IMSA.png', licenseClass: 'A'},
        {name: 'IMSA iRacing Series Fixed', src: '/iracing/2024s1/IMSAFixed.png', licenseClass: 'A'},
        {name: 'Formula A Grand Prix Series', src: '/iracing/2024s1/FormulaA.png', licenseClass: 'A'},
        {name: 'Formula A Grand Prix Series Fixed', src: '/iracing/2024s1/FormulaAFixed.png', licenseClass: 'A'},
]

export const iRacing2024S1OvalSeries: OfficialSeries[] = [
    {name: 'Street Stock Fanatec Series R', src: '/iracing/2024s1/StreetStock.png', licenseClass: 'Rookie'},
    {name: 'Rookie Legends VRS Cup', src: '/iracing/2024s1/RookieLegends.png', licenseClass: 'Rookie'},

    {name: 'ARCA Menards Series', src: '/iracing/2024s1/ARCASeries.png', licenseClass: 'D'},
    {name: 'Draft Master Fixed', src: '/iracing/2024s1/DraftMaster.png', licenseClass: 'D'},
    {name: 'CARS Late Model Stock Tour Fixed', src: '/iracing/2024s1/LateModelStockFixed.png', licenseClass: 'D'},
    {name: 'SK Modified Weekly Series Fixed', src: '/iracing/2024s1/SKModifiedFixed.png', licenseClass: 'D'},
    {name: 'SK Modified Weekly Series', src: '/iracing/2024s1/SKModifiedWeekly.png', licenseClass: 'D'},

    {name: 'NASCAR Class C Maconi Setup Shop Fixed', src: '/iracing/2024s1/NascarCFixed.png', licenseClass: 'C'},
    {name: 'NASCAR iRacing Class C', src: '/iracing/2024s1/NascarC.png', licenseClass: 'C'},
    {name: 'US Open Wheel C Dallara IR‑18 Fixed', src: '/iracing/2024s1/OpenWheelC.png', licenseClass: 'C'},
    {name: 'Gen 4 Cup Fixed', src: '/iracing/2024s1/Gen4CupFixed.png', licenseClass: 'C'},
    {name: 'Advanced Legends Cup', src: '/iracing/2024s1/AdvancedLegends.png', licenseClass: 'C'},
    {name: 'CARS Late Model Stock Tour', src: '/iracing/2024s1/LateModelStock.png', licenseClass: 'C'},
    {name: 'Street Stock Next Level Racing Series C', src: '/iracing/2024s1/StreetStockC.png', licenseClass: 'C'},
    {name: 'Super Late Model Series Fixed', src: '/iracing/2024s1/SuperLateModelFixed.png', licenseClass: 'C'},
    {name: 'Super Late Model Series', src: '/iracing/2024s1/SuperLateModel.png', licenseClass: 'C'},
    {name: 'NASCAR Tour Modified Series Fixed', src: '/iracing/2024s1/NascarTourModifiedFixed.png', licenseClass: 'C'},
    {name: 'NASCAR Tour Modified Series ', src: '/iracing/2024s1/NascarTourModified.png', licenseClass: 'C'},

    {name: 'NASCAR Class B Fixed', src: '/iracing/2024s1/NascarBFixed.png', licenseClass: 'B'},
    {name: 'NASCAR iRacing Class B', src: '/iracing/2024s1/NascarB.png', licenseClass: 'B'},
    {name: 'NASCAR Legends Series', src: '/iracing/2024s1/NascarLegends.png', licenseClass: 'B'},
    {name: 'Sprint Car Cup', src: '/iracing/2024s1/SprintCarCup.png', licenseClass: 'B'},
    {name: 'Silver Crown Cup', src: '/iracing/2024s1/SilverCrownCup.png', licenseClass: 'B'},

    {name: 'NASCAR Class A Fixed', src: '/iracing/2024s1/NascarAFixed.png', licenseClass: 'A'},
    {name: 'NASCAR Class A', src: '/iracing/2024s1/NascarA.png', licenseClass: 'A'},
]

export const iRacing2024S1DirtOvalSeries: OfficialSeries[] = [
    {name: 'Rookie DIRTcar Street Stock Series Fixed', licenseClass: 'Rookie', src: ''},
    {name: 'Dirt Legends Cup', licenseClass: 'Rookie', src: ''},

    {name: 'DIRTcar 305 Sprint Car Fanatec Series', licenseClass: 'D'},
    {name: 'DIRTcar Limited Late Model Series', licenseClass: 'D'},
    {name: 'DIRTcar 358 Modified Engine Ice Series', licenseClass: 'D'},

    {name: 'DIRTcar Pro Late Model Series Fixed', licenseClass: 'C'},
    {name: 'DIRTcar Pro Late Model Series', licenseClass: 'C'},
    {name: 'SUPER DIRTcar Big Block Modified Series Fixed', licenseClass: 'C'},
    {name: 'SUPER DIRTcar Big Block Modified Series', licenseClass: 'C'},
    {name: 'DIRTcar 360 Sprint Car Carquest Series Fixed', licenseClass: 'C'},
    {name: 'DIRTcar 360 Sprint Car Carquest Series', licenseClass: 'C'},
    {name: 'Dirt Midget Cup Fixed', licenseClass: 'C'},
    {name: 'Dirt Midget Cup', licenseClass: 'C'},
    {name: 'DIRTcar Class C Street Stock Series Fixed', licenseClass: 'C'},
    {name: 'Dirt Super Late Model Tour Fixed', licenseClass: 'C'},
    {name: 'USAC 360 Sprint Car Series', licenseClass: 'C'},
    {name: 'Dirt 410 Sprint Car Tour Fixed', licenseClass: 'C'},

    {name: 'World of Outlaws Late Model Series Fixed', licenseClass: 'B'},
    {name: 'World of Outlaws Late Model Series', licenseClass: 'B'},
    {name: 'World of Outlaws Sprint Car Series Fixed', licenseClass: 'B'},
    {name: 'World of Outlaws Sprint Car Series', licenseClass: 'B'},
    {name: 'DIRTcar UMP Modified Series Fixed', licenseClass: 'B'},
    {name: 'AMSOIL USAC Sprint Car Fixed', licenseClass: 'B'},
]

export const iRacing2024S1DirtRoadSeries: OfficialSeries[] = [
    {name: 'Rookie Pro 2 Lite Off‑Road Racing Series Fixed', licenseClass: 'Rookie'},
    {name: 'Rookie iRX Volkswagen Beetle Lite Fixed', licenseClass: 'Rookie'},
    {name: 'iRX Volkswagen Beetle Lite', licenseClass: 'D'},
    {name: 'Pro 4 Off‑Road Racing Series Fixed', licenseClass: 'D'},
    {name: 'Rallycross Series Fixed', licenseClass: 'C'},
    {name: 'Pro 2 Off‑Road Racing Series Fixed', licenseClass: 'C'},
    {name: 'Rallycross Series', licenseClass: 'B'},
    {name: 'Pro 4 Off‑Road Racing Series', licenseClass: 'B'},
    {name: 'Pro 2 Off‑Road Racing Series', licenseClass: 'B'},
]